apiVersion: v1
kind: Secret
metadata:
  name: twitter-secret
stringData: 
  options.json: |
    {
      "SecretKey": "someSecretKey",
      "SecretValue": "someSecretValue",
      "TwitterClient": {
        "ClientId": "someTwitterClientId",
        "ClientSecret": "someTwitterClientSecret"
      }
    }
